esphome:
  name: acmelec-thermostat
  friendly_name: acmelec-thermostat

esp8266:
  board: esp12e

logger:
  baud_rate: 0

api:
  password: ""
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:

climate:
  - platform: tuya
    name: "Floor heater"
    switch_datapoint: 1
    target_temperature_datapoint: 16
    current_temperature_datapoint: 24
    icon: "mdi:heating-coil"
    visual:
      temperature_step: 1.0

switch:
  - platform: "tuya"
    name: "Child lock"
    switch_datapoint: 40
    
    
select:
  - platform: "tuya"
    name: "Mode"
    enum_datapoint: 2
    optimistic: false
    options:
      0: "auto"
      1: "manual"

  - platform: "tuya"
    name: "Temp sensor position"
    enum_datapoint: 43
    optimistic: false
    options:
      0: "in"
      1: "out"
      2: "none"

sensor:
  - platform: uptime
    name: Uptime
