esphome:
  name: esp32-c3-02
  friendly_name: astra
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

logger:
  level: VERBOSE
  logs:
    canbus: VERBOSE
    mcp2515: VERBOSE


api:
  password: ""
  reboot_timeout: 0s
ota:
  password: ""
  safe_mode: false

wifi:
  ssid: !secret wifi_hotspot_ssid
  password: !secret wifi_hotspot_password
  fast_connect: true
  power_save_mode: none
  use_address: 10.4.0.4
  output_power: 8.5
  reboot_timeout: 0s

time:
  - platform: sntp
    timezone: Europe/Moscow

wireguard: !include wg.yaml

web_server:

uart:
  - rx_pin: GPIO9
    tx_pin: GPIO10
    baud_rate: 9600
    id: fs_uart
    debug:
      direction: BOTH
      dummy_receiver: true
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

spi:
  id: McpSpi
  clk_pin: GPIO4
  mosi_pin: GPIO6
  miso_pin: GPIO5

binary_sensor:

canbus:
  - platform: mcp2515
    id: my_mcp2515
    spi_id: McpSpi
    cs_pin: GPIO7
    can_id: 4
    bit_rate: 33kbps
    clock: 8mhz
    on_frame:
      - can_id: 0x175
        then:
          - lambda: |-
              if(x.size() > 0) {
                switch(x[5]) {
                  case 0x40: id(b_play).press(); break;
                  case 0x04: id(b_next).press(); break;
                  case 0x05: id(b_prev).press(); break;
                }
              }
      - can_id: 0x445
        then:
          - lambda: |-
              if(x.size() > 0) {
                id(sens_temp_out).publish_state((float) x[1]/2-40);
              }
      - can_id: 0x500
        then:
          - lambda: |-
              if(x.size() > 0) {
                id(sens_voltage).publish_state((float) x[1]/8);
              }
      - can_id: 0x145
        then:
          - lambda: |-
              if(x.size() > 0) {
                id(sens_coolant).publish_state((float) x[3]-40);
              }

light:
  - platform: binary
    name: "Indicator"
    id: indicator_light
    output: indicator_output
    restore_mode: ALWAYS_ON

output:
  - id: indicator_output
    platform: gpio
    pin: GPIO8
    inverted: true


sensor:
  - platform: template
    name: "outside temp"
    id: sens_temp_out
    device_class: "temperature"
  - platform: template
    name: "voltage"
    id: sens_voltage
    device_class: "voltage"
  - platform: template
    name: "coolant"
    id: sens_coolant
    device_class: "temperature"

  - platform: uptime
    name: Uptime


switch:


button:
  - platform: restart
    name: "Reboot"

  - platform: template
    name: "UART test"
    on_press:
      - uart.write:
          id: fs_uart
          data: "AT+MN\r\n"
  - platform: template
    name: "play"
    id: b_play
    on_press:
      - uart.write:
          id: fs_uart
          data: "AT+MA\r\n"
  - platform: template
    name: "next"
    id: b_next
    on_press:
      - uart.write:
          id: fs_uart
          data: "AT+MD\r\n"
  - platform: template
    name: "prev"
    id: b_prev
    on_press:
      - uart.write:
          id: fs_uart
          data: "AT+ME\r\n"
  - platform: template
    name: "vol_up"
    on_press:
      - uart.write:
          id: fs_uart
          data: "AT+CK\r\n"
  - platform: template
    name: "vol_dn"
    on_press:
      - uart.write:
          id: fs_uart
          data: "AT+CL\r\n"


text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      address_0:
        name: ESP IP Address 0
      address_1:
        name: ESP IP Address 1
      address_2:
        name: ESP IP Address 2
      address_3:
        name: ESP IP Address 3
      address_4:
        name: ESP IP Address 4
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address