esphome:
  name: bk7231n-3gang-switch
  friendly_name: bk7231n-3gang-switch

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev

logger:
  baud_rate: 0
api:
  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
ota:
  platform: esphome
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  output_power: 20.5dbm
  power_save_mode: none

binary_sensor:
  - platform: gpio
    pin:
      number: P7
    id: button_1
    on_state:
      then:
        - light.toggle: light_1
  - platform: gpio
    pin:
      number: P15
    id: button_2
    on_state:
      then:
        - light.toggle: light_2
  - platform: gpio
    pin:
      number: P9
    id: button_3
    on_state:
      then:
        - light.toggle: led_01

output:
  - platform: gpio
    pin: P24
    id: relay_1
  - platform: gpio
    pin: P17
    id: relay_2
  - platform: gpio
    pin: P26
    id: relay_3
  - platform: libretiny_pwm
    frequency: 1000 Hz
    pin: P8
    id: rtttl_out
  - platform: libretiny_pwm
    frequency: 19531 Hz
    pin: P6
    id: light_pwm

light:
  - platform: binary
    name: "Left"
    id: light_1
    output: relay_1
  - platform: binary
    name: "Middle"
    id: light_2
    output: relay_2
  - platform: binary
    name: "Right"
    id: light_3
    output: relay_3
  - platform: monochromatic
    icon: mdi:led-off
    output: light_pwm
    name: "led"
    id: led_01
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_OFF

rtttl:
  output: rtttl_out

sensor:
  - platform: uptime
    name: Uptime
