esphome:
  name: bk7231n-dual-plug-01
  friendly_name: bk7231n-dual-plug-01

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:
  baud_rate: 0
api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

preferences:
  flash_write_interval: 15s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

switch:
  - platform: gpio
    id: socket_01
    pin: P26
    name: "Socket 01"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    id: socket_02
    pin: P24
    name: "Socket 02"
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin:
      number: P6
    id: button_1
    on_state:
      then:
        - switch.toggle: socket_01
        - switch.toggle: socket_02

sensor:
  - platform: hlw8012
    model: BL0937
    voltage_divider: 810 # def 2351 more is more
    sel_pin:
      number: P23
      inverted: true
    cf_pin:
      number: P7
      inverted: true
    cf1_pin:
      number: P8
      inverted: true
    current:
      name: "HLW8012 Current"
    voltage:
      name: "HLW8012 Voltage"
    power:
      name: "HLW8012 Power"
    energy:
      name: "HLW8012 Energy"
    update_interval: 5s
  - platform: internal_temperature
    name: "Internal Temperature"
  - platform: uptime
    name: Uptime

status_led:
  pin:
    number: P10
    inverted: true


#    {
#      "vendor": "Elworks",
#      "bDetailed": "0",
#      "name": "Smart Dual Socket",
#      "model": "CLY809M-GE",
#      "chip": "BK7231N",
#      "board": "CB2S",
#      "flags": "1024",
#      "keywords": [
#        "two sockets",
#        "power metering",
#        "two relays"
#      ],
#      "pins": {
#        "6": "Btn_Tgl_All;1",
#        "7": "BL0937CF;0",
#        "8": "BL0937CF1;0",
#        "10": "WifiLED_n;0",
#        "23": "BL0937SEL;0",
#        "24": "Rel;1",
#        "26": "Rel;2"
#      },
#      "command": "",
#      "image": "https://obrazki.elektroda.pl/2773645000_1707143046.jpg",
#      "wiki": "https://www.elektroda.com/rtvforum/topic4033779.html"
#    }