#TMWF02 fan module
esphome:
  name: bk7231t-fan
  friendly_name: bk7231t-fan

bk72xx:
  board: wb2s
  framework:
    version: dev

logger:
  baud_rate: 0
api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true


uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

tuya:

#  [10:36:30][C][tuya:041]: Tuya:
#  [10:36:30][C][tuya:056]:   Datapoint 1: switch (value: OFF)
#  [10:36:30][C][tuya:058]:   Datapoint 2: int value (value: 0)
#  [10:36:30][C][tuya:062]:   Datapoint 3: enum (value: 0)
#  [10:36:30][C][tuya:058]:   Datapoint 4: int value (value: 100)
#  [10:36:30][C][tuya:074]:   Product: '{"p":"kxtcfbazhsvjqcfz","v":"1.0.0","m":2}'

fan:
  - platform: "tuya"
    name: "fan"
    id: tuya_fan
    switch_datapoint: 1
    speed_datapoint: 4
    speed_count: 100

button:
  - platform: template
    name: "Preset 10%"
    on_press:
      - fan.turn_on:
          id: tuya_fan
          speed: 10
  - platform: template
    name: "Preset 20%"
    on_press:
      - fan.turn_on:
          id: tuya_fan
          speed: 20
  - platform: template
    name: "Preset 25%"
    on_press:
      - fan.turn_on:
          id: tuya_fan
          speed: 25
  - platform: template
    name: "Preset 30%"
    on_press:
      - fan.turn_on:
          id: tuya_fan
          speed: 30
  - platform: template
    name: "Preset 40%"
    on_press:
      - fan.turn_on:
          id: tuya_fan
          speed: 40
  - platform: template
    name: "Preset 50%"
    on_press:
      - fan.turn_on:
          id: tuya_fan
          speed: 50
  - platform: template
    name: "Preset 70%"
    on_press:
      - fan.turn_on:
          id: tuya_fan
          speed: 70
  - platform: template
    name: "Preset 100%"
    on_press:
      - fan.turn_on:
          id: tuya_fan
          speed: 100

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
  - platform: uptime
    name: Uptime

