esphome:
  name: c3-test
  friendly_name: c3-test
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

logger:
  baud_rate: 115200

api:
  password: ""
ota:
  safe_mode: false
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

button:
  - platform: restart
    name: "Reboot"
sensor:
  - platform: uptime
    name: Uptime

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output

output:
  - id: indicator_output
    platform: gpio
    pin: GPIO8
    inverted: true