esphome:
  name: c3-test
  friendly_name: c3-test
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino
    version: recommended


logger:
  baud_rate: 115200

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  output_power: 15dbm

i2c:
  sda: GPIO3
  scl: GPIO4
  scan: false
  frequency: 400kHz

font:
  - file: "fonts/4x6.bdf"
    id: f4x6
    size: 6
  - file: "fonts/5x8.bdf"
    id: f5x8
  - file: "fonts/10x20.bdf"
    id: f10x20
  - file: "fonts/helvR08.bdf"
    id: fh08

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    update_interval: 1ms
    lambda: |-
      it.printf(0, 0, id(f10x20), "%.1f", id(ntc_sensor).state);

button:
  - platform: restart
    name: "Reboot"
sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    #update_interval: 2s

  - platform: adc
    id: source_sensor
    pin:
      number: GPIO1
      mode:
        input: true
        pullup: false
        pulldown: false
    update_interval: 1s
    name: ADC Sensor
    attenuation: auto

  - platform: resistance
    sensor: source_sensor
    configuration: UPSTREAM
    resistor: 4.708kOhm
    name: Resistance Sensor
    id: resistance_sensor

  - platform: ntc
    sensor: resistance_sensor
    id: ntc_sensor
    name: NTC
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm

switch:
  platform: gpio
  pin: GPIO0
  restore_mode: ALWAYS_ON
  name: ntc power
  inverted: false


light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_ON
    internal: true

output:
  - id: indicator_output
    platform: gpio
    pin:
      number: GPIO8
      ignore_strapping_warning: true
    inverted: true