esphome:
  name: c3-test
  friendly_name: c3-test
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino
    version: recommended


logger:
  baud_rate: 115200

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

i2c:
  sda: GPIO3
  scl: GPIO4
  scan: false
  frequency: 400kHz

font:
  - file: "fonts/4x6.bdf"
    id: f4x6
    size: 6
  - file: "fonts/5x8.bdf"
    id: f5x8
  - file: "fonts/10x20.bdf"
    id: f10x20
  - file: "fonts/helvR08.bdf"
    id: fh08

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    update_interval: 1ms
    lambda: |-
      it.printf(0, 0, id(f10x20), "%.1f", id(counter_total).state);
      return;
      if (id(hall_01).state == true) {
        it.print(0, 0, id(f10x20), "ON");
      } else if (id(hall_01).state == false) {
        it.print(0, 0, id(f10x20), "OFF");
      } else {
        it.print(0, 0, id(f10x20), "UNK");
      }

button:
  - platform: restart
    name: "Reboot"
sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    #update_interval: 2s

  - platform: pulse_meter
    pin:
      number: GPIO1
      mode:
        input: true
        pullup: false
        pulldown: false
      inverted: true
    id: hall_01
    name: "counter speed"
    #update_interval: 1s
    timeout: 10s
    internal_filter_mode: PULSE
    total:
      name: "counter total"
      id: counter_total
    on_raw_value:
      - light.toggle:
          id: indicator_light

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_ON
    internal: true

output:
  - id: indicator_output
    platform: gpio
    pin:
      number: GPIO8
      ignore_strapping_warning: true
    inverted: true