esphome:
  name: d1-co2
  friendly_name: d1-co2
  includes:
    # https://github.com/LeoDJ/ESPHome_Nodes/tree/main/CM1106_CO2_Sensor
    - "cm1106.h"
    
esp8266:
  board: d1_mini

logger:
  baud_rate: 0

api:
  password: ""
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

i2c:
  sda: D1
  scl: D2
  scan: true
  id: bus_a

uart:
  - rx_pin: D7
    tx_pin: D6
    baud_rate: 9600
    id: cm1106_uart

  - rx_pin: D5
    tx_pin: D8 # not connected
    baud_rate: 9600
    id: pm_2_5_uart

  - rx_pin: RX
    tx_pin: TX
    baud_rate: 9600
    id: s8_uart
    
light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_OFF

output:
  - id: indicator_output
    platform: gpio
    pin: D4
    inverted: true

sensor:
  - platform: custom
    lambda: |-
      auto cm1106Sensor = new CM1106Sensor(id(cm1106_uart), 10000);
      App.register_component(cm1106Sensor);
      return {cm1106Sensor};
    sensors:
    - name: "CO₂ cm11"
      accuracy_decimals: 0
      unit_of_measurement: "ppm"
      device_class: "carbon_dioxide"
      icon: "mdi:molecule-co2"
      filters:
        - throttle: 15s

  - platform: senseair
    co2:
      name: "CO₂ S8"
    id: co2_s8
    update_interval: 20s
    uart_id: s8_uart

  - platform: bh1750
    name: "Illuminance"
    address: 0x23
    update_interval: 60s

  - platform: pm1006
    pm_2_5:
      name: "PM 2.5µm"
    update_interval: 20s
    uart_id: pm_2_5_uart

  - platform: uptime
    name: Uptime

switch:
  - platform: custom
    lambda: |-
      auto cm1106Calib = new CM1106CalibrateSwitch(id(cm1106_uart));
      App.register_component(cm1106Calib);
      return {cm1106Calib};
    switches:
    - name: "CM1106 Zero Calibration"
  - platform: template
    name: "CO₂ S8 ABC"
    optimistic: true
    restore_mode: DISABLED
    on_turn_on:
      - senseair.abc_enable: co2_s8
    on_turn_off:
      - senseair.abc_disable: co2_s8


button:
  - platform: restart
    name: "Reboot"
  - platform: template
    name: "CO₂ S8 background calibration"
    on_press:
      - senseair.background_calibration: co2_s8