esphome:
  name: d1-co2
  includes:
    - "cm1106.h"
    
esp8266:
  board: d1_mini

logger:

api:
  password: ""
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true


uart:
  - rx_pin: D7
    tx_pin: D6
    baud_rate: 9600
    id: cm1106_uart

  - rx_pin: D2
    tx_pin: D1
    baud_rate: 9600
    id: s8_uart
    
sensor:
  - platform: custom
    lambda: |-
      auto cm1106Sensor = new CM1106Sensor(id(cm1106_uart), 10000);
      App.register_component(cm1106Sensor);
      return {cm1106Sensor};
    sensors:
    - name: "CO₂ cm11"
      accuracy_decimals: 0
      unit_of_measurement: "ppm"
      device_class: "carbon_dioxide"
      icon: "mdi:molecule-co2"
  - platform: senseair
    co2:
      name: "CO₂ S8"
    update_interval: 15s
    uart_id: s8_uart

switch:
  - platform: custom
    lambda: |-
      auto cm1106Calib = new CM1106CalibrateSwitch(id(cm1106_uart));
      App.register_component(cm1106Calib);
      return {cm1106Calib};
    switches:
    - name: "CM1106 Zero Calibration"