esphome:
  name: ld2410

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

api:
  password: ""
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

uart:
  id: uart1
  tx_pin: D3
  rx_pin: D2
  baud_rate: 9600
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart

binary_sensor:
  - platform: ld2410
    has_target:
      name : "presence"
    has_moving_target:
      name : "movement"
    has_still_target:
      name: "still"

sensor:
  - platform: ld2410
    moving_distance:
      name : "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
       name: "Move Energy"
    still_energy:
      name: "Still Energy"
    detection_distance:
      name: "Distance Detection"
      

    