esphome:
  name: d1-test
  friendly_name: d1-test

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    internal: false
    restore_mode: ALWAYS_ON

output:
  - id: indicator_output
    platform: gpio
    pin: GPIO2
    inverted: true

sensor:

  - platform: uptime
    name: Uptime

button:
  - platform: restart
    name: "Reboot"
