esphome:
  name: diy-relay-1ch
  friendly_name: diy-relay-1ch

esp8266:
  board: esp12e

logger:
  baud_rate: 0

api:
  password: ""
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

switch:
  - platform: gpio
    pin: GPIO5
    name: "Relay"
    restore_mode: ALWAYS_OFF

light:
  - platform: binary
    name: "Indicator"
    output: indicator_output
#  - platform: binary
#    name: "Onboard led"
#    output: onboard_led_output
#    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO2
    inverted: true

output:
  - id: indicator_output
    platform: gpio
    pin: GPIO16
    inverted: true
#  - id: onboard_led_output
#    platform: gpio
#    pin: GPIO2
#    inverted: true


sensor:
  - platform: uptime
    name: Uptime
