esphome:
  name: esp-ups
  friendly_name: "ESP UPS"
  includes:
    - "esphome-custom/ninebattery.h"
    
esp8266:
  board: esp12e

logger:

api:
  password: ""
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

switch:
  - platform: gpio
    pin: GPIO5
    name: "Charge"
    icon: "mdi:home-lightning-bolt"
    restore_mode: ALWAYS_OFF
    
  - platform: gpio
    pin: GPIO4
    name: "Force discharge"
    icon: "mdi:home-lightning-bolt-outline"
    restore_mode: ALWAYS_OFF
    
light:
  - platform: binary
    name: "Indicator"
    output: indicator_output

output:
  - id: indicator_output
    platform: gpio
    pin: GPIO16
    inverted: true
    
    
#14i, 12o
uart:
  - rx_pin:
      number: RX
      mode: INPUT_PULLUP
    tx_pin:
      number: TX
      mode: OUTPUT
    baud_rate: 115200
    id: ninebattery_uart
    
    
sensor:
  - platform: custom
    lambda: |-
      auto nb = new NinebatterySensor(id(ninebattery_uart), 1000);
      App.register_component(nb);
      return {nb->s_status, nb->s_remaining_capacity_perc, nb->s_remaining_capacity, nb->s_actual_capacity, nb->s_factory_capacity, nb->s_current, nb->s_voltage, nb->s_power, nb->s_temperature_zone_0, nb->s_temperature_zone_1, nb->s_voltage_cell_0, nb->s_voltage_cell_1, nb->s_voltage_cell_2, nb->s_voltage_cell_3, nb->s_voltage_cell_4, nb->s_voltage_cell_5, nb->s_voltage_cell_6, nb->s_voltage_cell_7, nb->s_voltage_cell_8, nb->s_voltage_cell_9 };
    sensors:
    - name: "Battery status"
      entity_category: "diagnostic"
      icon: "mdi:battery-unknown"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Remaining capacity (perc)"
      device_class: "battery"
      unit_of_measurement: "%"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Remaining capacity"
      id: "remaining_capacity_perc"
      device_class: "energy"
      unit_of_measurement: "mAh"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Actual capacity"
      device_class: "energy"
      unit_of_measurement: "mAh"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Factory capacity"
      device_class: "energy"
      unit_of_measurement: "mAh"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Current"
      device_class: "current"
      unit_of_measurement: "A"
      accuracy_decimals: 3
      filters:
        - throttle: 15s
    - name: "Voltage"
      device_class: "voltage"
      unit_of_measurement: "V"
      accuracy_decimals: 3
      filters:
        - throttle: 15s
    - name: "Power"
      device_class: "power"
      unit_of_measurement: "W"
      accuracy_decimals: 3
      filters:
        - throttle: 15s
    - name: "Temperature zone 0"
      device_class: "temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Temperature zone 1"
      device_class: "temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Cell 0 Voltage"
      device_class: "voltage"
      unit_of_measurement: "mV"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Cell 1 Voltage"
      device_class: "voltage"
      unit_of_measurement: "mV"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Cell 2 Voltage"
      device_class: "voltage"
      unit_of_measurement: "mV"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Cell 3 Voltage"
      device_class: "voltage"
      unit_of_measurement: "mV"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Cell 4 Voltage"
      device_class: "voltage"
      unit_of_measurement: "mV"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Cell 5 Voltage"
      device_class: "voltage"
      unit_of_measurement: "mV"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Cell 6 Voltage"
      device_class: "voltage"
      unit_of_measurement: "mV"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Cell 7 Voltage"
      device_class: "voltage"
      unit_of_measurement: "mV"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Cell 8 Voltage"
      device_class: "voltage"
      unit_of_measurement: "mV"
      accuracy_decimals: 0
      filters:
        - throttle: 15s
    - name: "Cell 9 Voltage"
      device_class: "voltage"
      unit_of_measurement: "mV"
      accuracy_decimals: 0
      filters:
        - throttle: 15s

text_sensor:
  - platform: custom
    lambda: |-
      auto nbs = new NinebatterySerialSensor(1000);
      App.register_component(nbs);
      return {nbs->s_serial};
    text_sensors:
    - name: "Serial"
      icon: "mdi:identifier"
      entity_category: "diagnostic"
