# kitfort kt-6723 controller replacement
esphome:
  name: esp-kettle
  friendly_name: esp-kettle
  on_boot:
    priority: 500
    then:
      switch.turn_on: buttons_lock

esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: esp-idf

logger:
  baud_rate: 0
  level: WARN

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

preferences:
  flash_write_interval: 15s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

udp:
packet_transport:
  platform: udp
  update_interval: 1s
  providers:
    - name: esp32-ld2410-v2

time:
  - platform: sntp
    id: esptime
    timezone: Europe/Moscow

i2c:
  sda: GPIO18
  scl: GPIO16
  scan: true
  frequency: 50kHz

esp32_touch:
  setup_mode: false
  measurement_duration: 0.25ms
  sleep_duration: 0.5ms

font:
  - file: "fonts/4x6.bdf"
    id: f4x6
    size: 6
  - file: "fonts/5x8.bdf"
    id: f5x8
    size: 8
  - file: "fonts/10x20.bdf"
    id: f10x20
    size: 20
  - file: "fonts/helvR08.bdf"
    id: fh08

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    address: 0x3C
    update_interval: 1s

    lambda: |-
      //it.print(0, -3, id(f10x20), "11234");
      //it.print(0, 16, id(f10x20), "11234");
      
      bool offline = id(presence).state == false;
      
      if(id(display_override).state) {
          if(id(display_power).state == false) {
              it.print(rand() % 100, rand() % 28, id(f4x6), "Who are you?");
              return;              
          }
      } else {
          if(!isnan(id(kitchen_presence).state) && id(kitchen_presence).state == false) {
              it.print(rand() % 100, rand() % 28, id(f4x6), "Who are you?");
              return;              
          }
      }

      esphome::ESPTime now = id(esptime).now();
      it.strftime(80, -3, id(f10x20), "%H", now);
      it.print(98, -3, id(f10x20), ":");
      it.strftime(106, -3, id(f10x20), "%M", now);
      
      if (!offline) {
          it.printf(0, -3, id(f10x20), "%.0f째C", id(temp).state);
      } else {
          it.printf(0, -3, id(f10x20), "Offline");    
      }
      it.printf(0, 16, id(f10x20), "%.2fL", id(volume).state);

      it.printf(128, 22, id(fh08), TextAlign::TOP_RIGHT, "Filter: %.2fL", id(water_usage).state);


switch:
  - platform: gpio
    id: water_pump
    pin: GPIO33
    name: "water pump"
    restore_mode: ALWAYS_OFF
    internal: true

  - platform: gpio
    id: boil
    pin:
      number: GPIO17
      inverted: true
    restore_mode: ALWAYS_OFF
    internal: true

  - platform: template
    id: boil_safe
    name: "boil"
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      then:
        - script.execute: boil_safe_on
    on_turn_off:
      then:
        - script.execute: boil_off

  - platform: template
    id: buttons_lock
    name: "buttons lock"
    optimistic: true
    restore_mode: ALWAYS_ON
    on_turn_off:
      - script.execute: light_turn_on_power
      - script.execute: light_dim_mode
      - script.execute: light_dim_fire
      - script.execute: light_dim_pump
      - switch.turn_on: display_override
      - switch.turn_on: display_power
      - delay: 1min
      - switch.turn_on: buttons_lock
    on_turn_on:
      - script.execute: light_dim_power
      - script.execute: light_dim_mode
      - script.execute: light_dim_fire
      - script.execute: light_dim_pump
      - switch.turn_off: display_override
      - switch.turn_off: display_power

  - platform: template
    optimistic: true
    id: display_override
    restore_mode: ALWAYS_OFF
    name: "display override"
    icon: "mdi:monitor-lock"
    entity_category: diagnostic
  - platform: template
    optimistic: true
    id: display_power
    name: "display power"
    icon: "mdi:monitor"
    entity_category: diagnostic

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic

  - platform: template
    name: Autorun
    on_press:
      then:
        - script.execute: autorun

binary_sensor:
  - platform: gpio
    id: water_presence
    name: "water presence"
    pin:
      number: GPIO21
      inverted: true
      mode:
        input: true
    on_press:
      - script.execute: boil_check_unsafe
    on_release:
      - script.execute: boil_check_unsafe

  - platform: packet_transport
    provider: esp32-ld2410-v2
    name: "kitchen presence"
    remote_id: presence
    id: kitchen_presence
    internal: true
  - platform: template
    name: "kettle presence"
    id: presence
    icon: "mdi:kettle-alert"
    lambda: |-
      if (id(temp).state <= 10) {
          return false;
      }
      return true;

  - platform: esp32_touch
    name: "button power"
    pin: GPIO2
    threshold: 1000
    internal: true
    on_press:
      then:
        - switch.toggle: buttons_lock

  - platform: esp32_touch
    name: "button mode"
    pin: GPIO3
    threshold: 1000
    internal: true
    on_press:
      then:
        - if:
            condition:
              - lambda: 'return id(boil).state == false;'
              - lambda: 'return id(buttons_lock).state == false;'
            then:
              - script.execute: autorun
            else:
              - script.execute: boil_off

  - platform: esp32_touch
    name: "button fire"
    internal: true
    pin: GPIO4
    threshold: 1000
    on_press:
      then:
        - if:
            condition:
              - lambda: 'return id(boil).state == false;'
              - lambda: 'return id(buttons_lock).state == false;'
            then:
              - script.execute: boil_safe_on
            else:
              - script.execute: boil_off

  - platform: esp32_touch
    name: "button pump"
    pin: GPIO5
    threshold: 1000
    internal: true
    on_press:
      then:
        - if:
            condition:
              - lambda: 'return id(boil).state == false;'
              - lambda: 'return id(buttons_lock).state == false;'
            then:
              - script.execute: water_pump_on
    on_release:
      then:
        - script.execute: water_pump_off

sensor:
  - platform: uptime
    name: Uptime
  - platform: internal_temperature
    name: "Internal Temperature"

#  - platform: pulse_meter
#    id: freq
#    name: "input freq"
#    internal: true
#    pin:
#      number: GPIO36
#      inverted: true
#      mode:
#        input: true
#        pulldown: true

  - platform: resistance
    sensor: adc_sensor
    configuration: DOWNSTREAM
    resistor: 150kOhm
    name: Resistance Sensor
    id: resistance_sensor
    internal: true

  - platform: adc
    internal: true
    id: adc_sensor
    pin:
      number: GPIO1
      mode:
        input: true
        pullup: false
        pulldown: false
    update_interval: 0.1s
    name: ADC Sensor
    attenuation: 12db

  - platform: ntc
    sensor: resistance_sensor
    calibration:
      - 175387 Ohm -> 27.5째C
      - 55958 Ohm -> 51.5째C
      - 10096 Ohm -> 97째C
    name: "Water Temperature"
    id: temp
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5

  - platform: hx711
    name: "Water Volume"
    device_class: "volume_storage"
    unit_of_measurement: "L"
    accuracy_decimals: 2
    dout_pin: GPIO39
    clk_pin: GPIO40
    gain: 128
    update_interval: 0.1s
    id: volume
    filters:
      - calibrate_linear:
          - 835640 -> 0
          - 1064652 -> 1
      - sliding_window_moving_average:
          window_size: 5
          send_every: 10
  - platform: template
    name: "Water Previous volume"
    id: previous_volume
    unit_of_measurement: "L"
    accuracy_decimals: 2
    update_interval: 1s
    internal: true

  - platform: homeassistant
    name: "Filtered water volume"
    entity_id: sensor.watermeter_filtered_water_usage
    id: water_usage

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_ON
    internal: true

  - platform: monochromatic
    output: backlight_1_out
    name: "backlight blue"
    default_transition_length: 0s
    internal: true
  - platform: monochromatic
    output: backlight_2_out
    name: "backlight yellow"
    default_transition_length: 0s
    internal: true
  - platform: monochromatic
    output: led_1_out
    name: led_button_80
    default_transition_length: 0s
    internal: true
  - platform: monochromatic
    output: led_2_out
    id: led_mode
    name: led_button_mode
    default_transition_length: 0s
    internal: true
  - platform: monochromatic
    output: led_3_out
    name: led_button_fire
    id: led_fire
    internal: true
    default_transition_length: 0s
  - platform: monochromatic
    output: led_4_out
    name: led_button_pump
    id: led_pump
    default_transition_length: 0s
    internal: true
  - platform: monochromatic
    output: led_5_out
    name: led_button_90
    default_transition_length: 0s
    internal: true
  - platform: monochromatic
    output: led_6_out
    name: led_button_100
    default_transition_length: 0s
    internal: true
  - platform: monochromatic
    output: led_7_out
    name: led_button_power
    id: led_power
    default_transition_length: 0s
    internal: true

output:
  - id: indicator_output
    platform: gpio
    pin: GPIO15
    inverted: false

#  - platform: ledc
#    pin: GPIO17
#    frequency: 50 Hz
#    id: simistor_out

  - platform: ledc
    pin:
      number: GPIO35
      inverted: false
    frequency: 1000 Hz
    id: backlight_1_out

  - platform: ledc
    pin:
      number: GPIO38
      inverted: false
    frequency: 1000 Hz
    id: backlight_2_out

  - platform: ledc
    frequency: 1000 Hz
    id: led_1_out
    pin:
      number: GPIO11
      mode:
        output: true
    inverted: false
    channel: 1
    phase_angle: 0
  - platform: ledc
    frequency: 1000 Hz
    id: led_2_out
    pin:
      number: GPIO7
      mode:
        output: true
    inverted: false
    channel: 2
    phase_angle: 0
  - platform: ledc
    frequency: 1000 Hz
    id: led_3_out
    pin:
      number: GPIO8
      mode:
        output: true
    inverted: false
    channel: 3
    phase_angle: 0
  - platform: ledc
    frequency: 1000 Hz
    id: led_4_out
    pin:
      number: GPIO13
      mode:
        output: true
    inverted: false
    channel: 4
    phase_angle: 0
  - platform: ledc
    frequency: 1000 Hz
    id: led_5_out
    pin:
      number: GPIO12
      mode:
        output: true
    inverted: false
    channel: 5
    phase_angle: 0
  - platform: ledc
    frequency: 1000 Hz
    id: led_6_out
    pin:
      number: GPIO9
      mode:
        output: true
    inverted: false
    channel: 6
    phase_angle: 0
  - platform: ledc
    frequency: 1000 Hz
    id: led_7_out
    pin:
      number: GPIO10
      mode:
        output: true
    inverted: false
    channel: 7
    phase_angle: 0

interval:
  - interval: 0.1s
    then:
      - script.execute: boil_check_unsafe
      - script.execute: water_pump_check_unsafe

script:
  - id: boil_on
    then:
      - script.execute: light_turn_on_fire
      - switch.turn_on: display_override
      - switch.turn_on: display_power
      - lambda: 'id(boil_safe).publish_state(true);'
      - switch.turn_on: boil
  - id: boil_off
    then:
      - switch.turn_off: boil
      - script.execute: light_dim_fire
      - switch.turn_off: display_override
      - switch.turn_off: display_power
      - lambda: 'id(boil_safe).publish_state(false);'

  - id: boil_check_unsafe
    then:
      - if:
          any:
            - lambda: 'return id(temp).state >= 99;'
            - lambda: 'return id(water_presence).state == false;'
            - lambda: 'return id(volume).state <= 0.22;'
          then:
            - script.execute: boil_off
  - id: boil_safe_on
    then:
      - if:
          condition:
            - lambda: 'return id(temp).state < 99;'
            - lambda: 'return id(water_presence).state == true;'
            - lambda: 'return id(volume).state >= 0.55 || id(water_pump).state == true;'
          then:
            - script.execute: boil_on
          else:
            - script.execute: boil_off

  - id: water_pump_on
    then:
      - if:
          condition:
            - lambda: 'return id(presence).state == true;'
            - lambda: 'return id(volume).state < 0.92;'
          then:
            - lambda: 'id(previous_volume).publish_state(id(volume).state);'
            - script.execute: light_turn_on_pump
            - switch.turn_on: water_pump
  - id: water_pump_off
    then:
      - switch.turn_off: water_pump
      - script.execute: light_dim_pump

  - id: water_pump_check_unsafe
    then:
      - if:
          any:
            - lambda: 'return id(presence).state == false;'
            - lambda: 'return isnan(id(presence).state);'
            - lambda: 'return id(volume).state >= 0.92;'
          then:
            - script.execute: water_pump_off

  - id: autorun
    then:
      - script.execute: light_turn_on_mode
      - script.execute: water_pump_on
      - if:
          condition:
            - lambda: 'return id(volume).state < 0.2;'
          then:
            - delay: 10s
      - script.execute: boil_safe_on
      - delay: 5s
      - script.execute: light_dim_mode

  - id: light_turn_on_power
    then:
      - light.turn_on:
          id: led_power
          brightness: 100%

  - id: light_dim_power
    then:
      - light.turn_on:
          id: led_power
          brightness: 30%

  - id: light_turn_on_pump
    then:
      - light.turn_on:
          id: led_pump
          brightness: 100%

  - id: light_dim_pump
    then:
      - if:
          condition:
            - lambda: 'return id(water_pump).state == true;'
          then:
            - script.stop: light_dim_pump
      - if:
          condition:
            - lambda: 'return id(buttons_lock).state == false;'
          then:
            - light.turn_on:
                id: led_pump
                brightness: 30%
          else:
            - light.turn_off: led_pump

  - id: light_turn_on_mode
    then:
      - light.turn_on:
          id: led_mode
          brightness: 100%

  - id: light_dim_mode
    then:
      - if:
          condition:
            - lambda: 'return id(buttons_lock).state == false;'
          then:
            - light.turn_on:
                id: led_mode
                brightness: 30%
          else:
            - light.turn_off: led_mode


  - id: light_turn_on_fire
    then:
      - light.turn_on:
          id: led_fire
          brightness: 100%

  - id: light_dim_fire
    then:
      - if:
          condition:
            - lambda: 'return id(boil).state == true;'
          then:
            - script.stop: light_dim_fire
      - if:
          condition:
            - lambda: 'return id(buttons_lock).state == false;'
          then:
            - light.turn_on:
                id: led_fire
                brightness: 30%
          else:
            - light.turn_off: led_fire

