# kitfort kt-6723 controller replacement
esphome:
  name: esp-kettle
  friendly_name: esp-kettle

esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: esp-idf

logger:
  baud_rate: 0
api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

preferences:
  flash_write_interval: 15s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

time:
  - platform: sntp
    id: esptime
    timezone: Europe/Moscow

i2c:
  sda: GPIO18
  scl: GPIO16
  scan: true
  frequency: 50kHz

esp32_touch:
  setup_mode: false
  measurement_duration: 0.25ms
  sleep_duration: 0.5ms

font:
  - file: "fonts/4x6.bdf"
    id: f4x6
    size: 6
  - file: "fonts/5x8.bdf"
    id: f5x8
    size: 8
  - file: "fonts/10x20.bdf"
    id: f10x20
    size: 20

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    address: 0x3C
    update_interval: 1ms

    lambda: |-
      it.print(0, -3, id(f10x20), "11234");
      it.print(0, 16, id(f10x20), "11234");

      esphome::ESPTime now = id(esptime).now();
      it.strftime(80, -3, id(f10x20), "%H", now);
      it.print(98, -3, id(f10x20), ":");
      it.strftime(106, -3, id(f10x20), "%M", now);

switch:
  - platform: gpio
    id: water_pump
    pin: GPIO33
    name: "water pump"
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: boil
    pin:
      number: GPIO17
      inverted: true
    name: "boil"
    restore_mode: ALWAYS_OFF


button:
  - platform: restart
    name: Restart
    entity_category: diagnostic


binary_sensor:
  - platform: gpio
    id: water_presence
    name: "water presence"
    pin:
      number: GPIO21
      inverted: true
      mode:
        input: true
  - platform: esp32_touch
    name: "Touch Pad 01"
    pin: GPIO2
    threshold: 1000
  - platform: esp32_touch
    name: "Touch Pad 02"
    pin: GPIO3
    threshold: 1000
  - platform: esp32_touch
    name: "Touch Pad 03"
    pin: GPIO4
    threshold: 1000
  - platform: esp32_touch
    name: "Touch Pad 04"
    pin: GPIO5
    threshold: 1000


sensor:
  - platform: uptime
    name: Uptime

#  - platform: pulse_meter
#    id: freq
#    name: "input freq"
#    internal: true
#    pin:
#      number: GPIO36
#      inverted: true
#      mode:
#        input: true
#        pulldown: true

  - platform: resistance
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 150kOhm
    name: Resistance Sensor
    id: resistance_sensor

  - platform: adc
    id: source_sensor
    pin:
      number: GPIO1
      mode:
        input: true
        pullup: false
        pulldown: false
    update_interval: 1s
    name: ADC Sensor
    attenuation: auto

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_ON
    internal: true

  - platform: monochromatic
    output: backlight_1_out
    name: "backlight blue"
    default_transition_length: 0s
  - platform: monochromatic
    output: backlight_2_out
    name: "backlight yellow"
    default_transition_length: 0s
  - platform: monochromatic
    output: led_1
    name: led_1
    default_transition_length: 0s
  - platform: monochromatic
    output: led_2
    name: led_2
    default_transition_length: 0s
  - platform: monochromatic
    output: led_3
    name: led_3
    default_transition_length: 0s
  - platform: monochromatic
    output: led_4
    name: led_4
    default_transition_length: 0s
  - platform: monochromatic
    output: led_5
    name: led_5
    default_transition_length: 0s
  - platform: monochromatic
    output: led_6
    name: led_6
    default_transition_length: 0s
  - platform: monochromatic
    output: led_7
    name: led_7
    default_transition_length: 0s


output:
  - id: indicator_output
    platform: gpio
    pin: GPIO15
    inverted: false

#  - platform: ledc
#    pin: GPIO17
#    frequency: 50 Hz
#    id: simistor_out

  - platform: ledc
    pin:
      number: GPIO35
      inverted: false
    frequency: 1000 Hz
    id: backlight_1_out

  - platform: ledc
    pin:
      number: GPIO38
      inverted: false
    frequency: 1000 Hz
    id: backlight_2_out

  - platform: ledc
    frequency: 1000 Hz
    id: led_1
    pin:
      number: GPIO11
      mode:
        output: true
    inverted: false
    channel: 1
    phase_angle: 0
  - platform: ledc
    frequency: 1000 Hz
    id: led_2
    pin:
      number: GPIO7
      mode:
        output: true
    inverted: false
    channel: 2
    phase_angle: 0
  - platform: ledc
    frequency: 1000 Hz
    id: led_3
    pin:
      number: GPIO8
      mode:
        output: true
    inverted: false
    channel: 3
    phase_angle: 0
  - platform: ledc
    frequency: 1000 Hz
    id: led_4
    pin:
      number: GPIO13
      mode:
        output: true
    inverted: false
    channel: 4
    phase_angle: 0
  - platform: ledc
    frequency: 1000 Hz
    id: led_5
    pin:
      number: GPIO12
      mode:
        output: true
    inverted: false
    channel: 5
    phase_angle: 0
  - platform: ledc
    frequency: 1000 Hz
    id: led_6
    pin:
      number: GPIO9
      mode:
        output: true
    inverted: false
    channel: 6
    phase_angle: 0
  - platform: ledc
    frequency: 1000 Hz
    id: led_7
    pin:
      number: GPIO10
      mode:
        output: true
    inverted: false
    channel: 7
    phase_angle: 0

