esphome:
  name: esp01-switch
  friendly_name: esp01-switch

esp8266:
  board: esp01_1m

logger:

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

switch:
  - platform: gpio
    pin: 2
    id: honk
    inverted: true
    name: "Honk"
    icon: "mdi:bullhorn"
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 2s
      - switch.turn_off: honk

sensor:
  - platform: uptime
    name: Uptime
