esphome:
  name: esp32-d1-test
  friendly_name: esp32-d1-test

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

logger:
  baud_rate: 0

api:
ota:
  platform: esphome

safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  post_connect_roaming: false
  power_save_mode: none

light:
  - platform: esp32_rmt_led_strip
    channel_colors: RGB
    chipset: ws2811
    pin: GPIO16
    num_leds: 6
    name: "RGB strip"
    default_transition_length: 1s


button:
  - platform: restart
    name: "Reboot"

sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  - platform: internal_temperature
    name: "Internal Temperature"

status_led:
  pin:
    number: GPIO2
    inverted: false
