esphome:
  name: esp32-c6-test
  friendly_name: esp32-c6-test
#  platformio_options:
#    platform: https://github.com/lucaskatayama/platform-espressif32.git#feat/seeed_xiao_esp32c6.json

esp32:
  board: seeed_xiao_esp32c6
  variant: esp32c6
  framework:
    type: esp-idf

logger:
#  baud_rate: 1152000
#  hardware_uart: USB_SERIAL_JTAG

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

button:
  - platform: restart
    name: "Reboot"
sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    #update_interval: 2s

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_ON
    internal: false

  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    chipset: ws2812
    pin: GPIO8
    num_leds: 1
    name: "RGB Led"

output:
  - id: indicator_output
    platform: gpio
    pin:
      number: GPIO15
    inverted: false

  - platform: gpio
    id: wifi_switch_enable
    pin: GPIO3
