esphome:
  name: esp32-epaper
  friendly_name: esp32-epaper

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

logger:
  baud_rate: 0

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

font:
  - file: 'fonts/10x20.bdf'
    id: font1

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14

display:
  - platform: waveshare_epaper
    cs_pin: GPIO15
    dc_pin: GPIO27
    busy_pin: GPIO25
    reset_pin: GPIO26
    model: 2.90in
    full_update_every: 30
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");


light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_ON

output:
  - id: indicator_output
    platform: gpio
    pin: GPIO2
    inverted: false

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
  - platform: uptime
    name: Uptime
