esphome:
  name: esp32-d1-test
  friendly_name: esp32-d1-test

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf


logger:
  baud_rate: 0

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

button:
  - platform: restart
    name: "Reboot"

sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  - platform: internal_temperature
    name: "Internal Temperature"

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_ON

output:
  - id: indicator_output
    platform: gpio
    pin:
      number: GPIO2
      ignore_strapping_warning: true
    inverted: false

