esphome:
  name: esp32-ble-proxy
  friendly_name: "esp32-ble-proxy"

external_components:
  source: github://regevbr/esphome@ld2410
  components: [ld2410]
  
  
esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

logger:

api:
  password: ""
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

bluetooth_proxy:

remote_receiver:
  - id: rc_receiver
    pin:
       number: GPIO16
    dump: rc_switch
    tolerance: 60%
    filter: 250us
    idle: 4ms
    buffer_size: 2kb
    
    
uart:
  id: ld2410_uart
  tx_pin: GPIO17
  rx_pin: GPIO21
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  id: ld2410_1

binary_sensor:
  - platform: remote_receiver
    name: "433_sw_left"
    filters:
      - delayed_off: 100ms
    rc_switch_raw:
      code: '011111010011011100000001'
  - platform: remote_receiver
    filters:
      - delayed_off: 100ms
    name: "433_sw_right"
    rc_switch_raw:
      code: '011111010011011100000100'
  - platform: remote_receiver
    filters:
      - delayed_off: 100ms
    name: "433_01"
    rc_switch_raw:
      code: '001010101010000010100100'
  - platform: remote_receiver
    filters:
      - delayed_off: 100ms
    name: "433_02"
    rc_switch_raw:
      code: '110101011111110100110100'
  - platform: remote_receiver
    filters:
      - delayed_off: 100ms
    name: "433_03"
    rc_switch_raw:
      code: '001000000111001001010100'
  - platform: remote_receiver
    filters:
      - delayed_off: 100ms
    name: "433_04"
    rc_switch_raw:
      code: '000101101010101000010100'
  - platform: remote_receiver
    filters:
      - delayed_off: 100ms
    name: "433_05"
    rc_switch_raw:
      code: '011011110100101100100100'
  - platform: remote_receiver
    filters:
      - delayed_off: 100ms
    name: "433_06"
    rc_switch_raw:
      code: '001111000000011100110100'
  - platform: remote_receiver
    filters:
      - delayed_off: 100ms
    name: "433_07"
    rc_switch_raw:
      code: '110010101001110011100100'
  - platform: remote_receiver
    filters:
      - delayed_off: 100ms
    name: "433_08"
    rc_switch_raw:
      code: '110010101001110011100101'


  - platform: ld2410
    ld2410_id: ld2410_1
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status

sensor:
  - platform: ld2410
    ld2410_id: ld2410_1
    light:
      name: light
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0_move_energy:
      name: g0 move energy
    g0_still_energy:
      name: g0 still energy
    g1_move_energy:
      name: g1 move energy
    g1_still_energy:
      name: g1 still energy
    g2_move_energy:
      name: g2 move energy
    g2_still_energy:
      name: g2 still energy
    g3_move_energy:
      name: g3 move energy
    g3_still_energy:
      name: g3 still energy
    g4_move_energy:
      name: g4 move energy
    g4_still_energy:
      name: g4 still energy
    g5_move_energy:
      name: g5 move energy
    g5_still_energy:
      name: g5 still energy
    g6_move_energy:
      name: g6 move energy
    g6_still_energy:
      name: g6 still energy
    g7_move_energy:
      name: g7 move energy
    g7_still_energy:
      name: g7 still energy
    g8_move_energy:
      name: g8 move energy
    g8_still_energy:
      name: g8 still energy
  - platform: uptime
    name: Uptime


switch:
  - platform: ld2410
    ld2410_id: ld2410_1
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"


number:
  - platform: ld2410
    ld2410_id: ld2410_1
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0_move_threshold:
      name: g0 move threshold
    g0_still_threshold:
      name: g0 still threshold
    g1_move_threshold:
      name: g1 move threshold
    g1_still_threshold:
      name: g1 still threshold
    g2_move_threshold:
      name: g2 move threshold
    g2_still_threshold:
      name: g2 still threshold
    g3_move_threshold:
      name: g3 move threshold
    g3_still_threshold:
      name: g3 still threshold
    g4_move_threshold:
      name: g4 move threshold
    g4_still_threshold:
      name: g4 still threshold
    g5_move_threshold:
      name: g5 move threshold
    g5_still_threshold:
      name: g5 still threshold
    g6_move_threshold:
      name: g6 move threshold
    g6_still_threshold:
      name: g6 still threshold
    g7_move_threshold:
      name: g7 move threshold
    g7_still_threshold:
      name: g7 still threshold
    g8_move_threshold:
      name: g8 move threshold
    g8_still_threshold:
      name: g8 still threshold
      
      
      
button:
  - platform: ld2410
    ld2410_id: ld2410_1
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params
      
      
text_sensor:
  - platform: ld2410
    ld2410_id: ld2410_1
    version:
      name: "firmware version"
    mac_address:
      name: "mac address"
      
      
select:
  - platform: ld2410
    ld2410_id: ld2410_1
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level