esphome:
  name: esp32-ble-tracker

esp32:
  board: esp32cam
  framework:
    type: arduino

logger:

api:
  password: ""
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

esp32_ble_tracker:
binary_sensor:
  - platform: ble_presence
    mac_address: FF:FF:10:10:F5:DE
    name: "BLE Green"
  - platform: ble_presence
    mac_address: FF:10:00:00:36:E6
    name: "BLE Pink"
    
sensor:
  - platform: ble_rssi
    mac_address: FF:FF:10:10:F5:DE
    name: "BLE Green RSSI"
  - platform: ble_rssi
    mac_address: FF:10:00:00:36:E6
    name: "BLE Pink RSSI"

