esphome:
  name: esp32-rc-car
  friendly_name: esp32-rc-car

esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: esp-idf
    version: recommended

logger:

api:
  password: ""
ota:
  password: ""

web_server:
  port: 80
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true


output:
  - platform: ledc
    pin: GPIO17
    id: gpio_pwm_main
    frequency: 1000 Hz
  - platform: ledc
    pin: GPIO40
    id: gpio_pwm_turn
    frequency: 1000 Hz

  - id: indicator_output
    platform: gpio
    pin: GPIO15
    inverted: false

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_ON

switch:
  - platform: gpio
    pin: 34
    name: "Move backward"
    restore_mode: ALWAYS_OFF
    id: sw_bw
    interlock: [sw_fw]
  - platform: gpio
    pin: 21
    name: "Move forward"
    restore_mode: ALWAYS_OFF
    id: sw_fw
    interlock: [sw_bw]

  - platform: gpio
    pin: 36
    name: "Turn left"
    restore_mode: ALWAYS_OFF
    id: sw_left
    interlock: [sw_right]
  - platform: gpio
    pin: 38
    name: "Turn right"
    restore_mode: ALWAYS_OFF
    id: sw_right
    interlock: [sw_left]

servo:
  - id: servo_main
    output: gpio_pwm_main
    min_level: 0%
    idle_level: 0%
    max_level: 100%
  - id: servo_turn
    output: gpio_pwm_turn
    min_level: 0%
    idle_level: 0%
    max_level: 100%

number:
  - platform: template
    name: Speed main
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    mode: box
    set_action:
      then:
        - servo.write:
            id: servo_main
            level: !lambda 'return x / 100.0;'
  - platform: template
    name: Speed turn
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    mode: box
    set_action:
      then:
        - servo.write:
            id: servo_turn
            level: !lambda 'return x / 100.0;'
