substitutions:
  tion_mac_address: c8:f3:89:cd:50:90
  node_name: esp32-bedroom
  friendly_name: $node_name
  node_add_mac_suffix: "false"
  board: esp32dev
  project_version: 2023.7.0
  project_branch: $project_version
  project_source: github://dentra/esphome-tion@$project_branch
  project_source_refresh: 12h
  project_id: tion
  framework_type: arduino
  vport_version: 2023.2.0
  vport_source: github://dentra/esphome-components@$vport_version
  vport_source_refresh: 1d

esp32:
  board: $board
  framework:
    type: $framework_type

esphome:
  name: $node_name
  friendly_name: $friendly_name
  name_add_mac_suffix: $node_add_mac_suffix
  project:
    name: "dentra.$project_id"
    version: "$project_version ($framework_type)"
  min_version: "2023.8.0" # can't use substitutions here
  platformio_options:
    build_flags:
      - -std=gnu++17
    build_unflags:
      - -std=gnu++11

external_components:
  - source: $vport_source
    components: [crash_info, etl, otax, vport, esp32_usb_dis]
    refresh: $vport_source_refresh
  - source: $project_source
    refresh: $project_source_refresh

preferences:
  flash_write_interval: 10min

logger:
  logs:
    esp-idf: INFO
    component: ERROR

esp32_ble_tracker:

ble_client:
  mac_address: $tion_mac_address
  id: tion_ble_client

ota:
  on_begin:
    then:
      lambda: id(tion_ble_client).set_enabled(false);

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

vport:
  - platform: tion_lt
    id: tionLt_ble_vport
    ble_client_id: tion_ble_client
    persistent_connection: true
    state_timeout: 15s
    disable_scan: true

climate:
  - platform: tion_lt
    id: tion_climate
    name: None # use friendly_name
    vport_id: tionLt_ble_vport
    buzzer:
      name: "Buzzer"
    led:
      name: "Led"
    outdoor_temperature:
      name: "Outdoor Temperature"
    heater_power:
      name: "Heater power"
    airflow_counter:
      name: "Airflow counter"
    filter_time_left:
      name: "Filter Time Left"
    filter_warnout:
      name: "Filter Warnout"
    version:
      name: "Version"
    presets:
      comfort : { fan_speed: 3, target_temperature: 10, mode: fan_only }
      eco : { fan_speed: 2, target_temperature: 10, mode: fan_only }
    boost_time:
      name: "Boost Time"
    boost_time_left:
      name: "Boost Time Left"
    update_interval: 60s

sensor:
  - platform: internal_temperature
    name: "ESP Temperature"
    entity_category: diagnostic
  - platform: wifi_signal
    name: "WiFi Signal"
  - platform: uptime
    name: Uptime

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic
