esphome:
  name: esp32-bedroom
  friendly_name: esp32-bedroom
  platformio_options:
    build_flags:
      - -std=gnu++17
    build_unflags:
      - -std=gnu++11

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://dentra/esphome-components@2023.2.0
    components: [crash_info, etl, otax, vport, esp32_usb_dis]
    refresh: 1d
  - source: github://dentra/esphome-tion@2023.7.0
    refresh: 1d

preferences:
  flash_write_interval: 10min

logger:
  logs:
    esp-idf: INFO
    component: ERROR

esp32_ble_tracker:

ble_client:
  mac_address: c8:f3:89:cd:50:90
  id: tion_ble_client

ota:
  on_begin:
    then:
      lambda: id(tion_ble_client).set_enabled(false);

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

vport:
  - platform: tion_lt
    id: tionLt_ble_vport
    ble_client_id: tion_ble_client
    persistent_connection: true
    state_timeout: 15s
    disable_scan: true

climate:
  - platform: tion_lt
    id: tion_climate
    name: None # use friendly_name
    vport_id: tionLt_ble_vport
    buzzer:
      name: "Buzzer"
    led:
      name: "Led"
    outdoor_temperature:
      name: "Outdoor Temperature"
    heater_power:
      name: "Heater power"
    airflow_counter:
      name: "Airflow counter"
    filter_time_left:
      name: "Filter Time Left"
    filter_warnout:
      name: "Filter Warnout"
    version:
      name: "Version"
    presets:
      comfort : { fan_speed: 3, target_temperature: 10, mode: fan_only }
      eco : { fan_speed: 2, target_temperature: 10, mode: fan_only }
    boost_time:
      name: "Boost Time"
    boost_time_left:
      name: "Boost Time Left"
    update_interval: 60s

sensor:
  - platform: internal_temperature
    name: "ESP Temperature"
    entity_category: diagnostic
  - platform: wifi_signal
    name: "WiFi Signal"
  - platform: uptime
    name: Uptime

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic
