esphome:
  name: esp32-cam
  friendly_name: esp32-cam

esp32:
  board: esp32cam
  framework:
    type: arduino

logger:

api:
  password: ""
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

light:
  - platform: binary
    name: "ESP32 internal led"
    output: internal_led
    id: light_internal

  - platform: monochromatic
    name: "ESP32 flash"
    output: light_output
    id: light_flash

  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    chipset: ws2812
    pin: GPIO12
    num_leds: 1
    rmt_channel: 1
    name: "RGB Led"
    
output:
  - id: light_output
    channel: 2
    platform: ledc
    pin: GPIO4
    
  - id: internal_led
    platform: gpio
    pin: GPIO33
    inverted: true

esp32_camera:
  name: ESP32 cam
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
#  resolution: 1600x1200
  resolution: 1024x768
  max_framerate: 5 fps
  brightness: 2
  jpeg_quality: 7

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

