esphome:
  name: esp32-s3-devboard
  friendly_name: esp32-s3-devboard

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

logger:
  baud_rate: 115200

api:
ota:
  platform: esphome

safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  post_connect_roaming: false
  power_save_mode: none
  output_power: 8.5dbm

button:
  - platform: restart
    name: "Reboot"

sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal Sensor"

output:
  - id: indicator_output_tx
    platform: gpio
    pin:
      number: GPIO43
    inverted: true
  # - id: indicator_output_rx
  #   platform: gpio
  #   pin:
  #     number: GPIO44
  #   inverted: true

light:
  - platform: esp32_rmt_led_strip
    channel_colors: GRB
    chipset: ws2812
    pin: GPIO48
    num_leds: 6
    name: "RGB Led"
    default_transition_length: 0s
    rmt_symbols: 48
    use_dma: false
    use_psram: false

  - platform: binary
    id: indicator_light_tx
    name: "Indicator TX"
    output: indicator_output_tx
    restore_mode: ALWAYS_OFF

  # - platform: binary
  #   id: indicator_light_rx
  #   name: "Indicator RX"
  #   output: indicator_output_rx
  #   restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO44
    inverted: true
