esphome:
  name: eth01-evo
  friendly_name: "eth01-evo"
  platformio_options:
    board_build.flash_mode: dio

external_components:
  # equivalent shorthand for GitHub pull request
  - source: github://pr#6861
    components: [ ethernet ]

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf
    version: latest
    platform_version: 6.5.0

logger:
  baud_rate: 115200
  hardware_uart: uart0

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
#  fast_connect: true

ethernet:
  type: DM9051
  clk_pin: GPIO07
  mosi_pin: GPIO10
  miso_pin: GPIO03
  cs_pin: GPIO09
  interrupt_pin: GPIO08
  reset_pin: GPIO06
  clock_speed: 8MHz


light:
  - platform: binary
    id: led_01
    name: "led 01"
    output: out_led_01
    restore_mode: ALWAYS_ON

  - platform: binary
    id: led_02
    name: "led 02"
    output: out_led_02
    restore_mode: ALWAYS_ON

output:
  - id: out_led_01
    platform: gpio
    pin: GPIO5
    inverted: true

  - id: out_led_02
    platform: gpio
    pin: GPIO2
    inverted: true

sensor:
  - platform: uptime
    name: Uptime