esphome:
  name: haier-climate
  friendly_name: haier-climate
  platformio_options:
    board_build.flash_mode: dio

  devices:
    - id: hvac
      name: "Air Conditioner"
    - id: lamp
      name: "Sun-like lamp"

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_CTRL_MODEM_SLEEP: y # low power mode

logger:
  baud_rate: 0
  logs:
    haier.climate: INFO
    haier.protocol: INFO

api:
ota:
  platform: esphome
safe_mode:
  disabled: true

uart:
  rx_pin: GPIO4
  tx_pin: GPIO3
  baud_rate: 9600
  id: ac_port

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  #output_power: 15dbm

one_wire:
  - platform: gpio
    pin: GPIO2

climate:
  - platform: haier
    id: haier_ac
    device_id: hvac
    protocol: smartair2
    name: Haier AC
    uart_id: ac_port
    wifi_signal: true
    display: true
    visual:
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    supported_modes:
      - 'OFF'
      #- HEAT_COOL
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    supported_swing_modes:
      - 'OFF'
      - VERTICAL
      - BOTH
    supported_presets:
      #- AWAY
      - BOOST
      - COMFORT
    on_status_message:
      then:
        - logger.log:
            level: INFO
            format: "New status message received, size=%d, subcmd=%02X%02X"
            args: [ 'data_size', 'data[0]', 'data[1]' ]

switch:
  - platform: haier
    health_mode:
      device_id: hvac
      name: Haier health mode
    display:
      device_id: hvac
      name: Haier display

button:
  - platform: template
    device_id: lamp
    name: "Start Sunrise"
    on_press:
      - script.execute: sunrise_script
  - platform: restart
    name: "Reboot"
sensor:
  - platform: dallas_temp
    address: 0x1500000627452828
    name: "heating"
  - platform: dallas_temp
    device_id: hvac
    address: 0x3b0000003e59e128
    name: "collant"
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
  - platform: internal_temperature
    name: "Internal Temperature"

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_ON
    internal: true

  - platform: cwww
    id: sunlike
    device_id: lamp
    name: "Sunlight"
    icon: "mdi:weather-sunny"
    cold_white: light_cold
    warm_white: light_warm
    cold_white_color_temperature: 5500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: false
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - id: light_warm
    platform: ledc
    pin: GPIO1
    frequency: 19531Hz
    min_power: 0.008 #$$\text{min\_power} = (\text{desired\_brightness})^{2.8}$$
    zero_means_zero: true
  - id: light_cold
    platform: ledc
    pin: GPIO0
    frequency: 19531Hz
    min_power: 0.008
    zero_means_zero: true

  - id: indicator_output
    platform: gpio
    pin:
      number: GPIO8
      ignore_strapping_warning: true
    inverted: true

number:
  - platform: template
    device_id: lamp
    name: "Sunrise Duration"
    id: sunrise_duration
    min_value: 1
    max_value: 60
    initial_value: 30
    step: 1
    unit_of_measurement: "min"
    optimistic: true
    restore_value: true

script:
  - id: sunrise_script
    mode: restart
    then:
      - light.control:
          id: sunlike
          state: ON
          brightness: 1%
          color_temperature: 2700K
          transition_length: 0s
      - delay: 5s
      - light.control:
          id: sunlike
          brightness: 100%
          color_temperature: 4500K
          transition_length: !lambda "return id(sunrise_duration).state * 60 * 1000;"