esphome:
  name: ld2410-v2-bathroom
  friendly_name: "ld2410-v2-bathroom"

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

api:
  password: ""
ota:
  password: ""
  safe_mode: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

uart:
  id: ld2410_uart
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600
  parity: NONE
  stop_bits: 1

dallas:
  - pin: GPIO5

ld2410:
  uart_id: ld2410_uart
  id: ld2410_1

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output

output:
  - id: indicator_output
    platform: gpio
    pin: GPIO2
    inverted: true

binary_sensor:
  - platform: ld2410
    ld2410_id: ld2410_1
    has_target:
      name: Presence
      on_press:
        then:
          - light.turn_on: indicator_light
      on_release:
        then:
          - light.turn_off: indicator_light
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status

sensor:
  - platform: dallas
    address: 0x820000003d6f0128
    name: "e_0x820000003d6f0128"
  - platform: dallas
    address: 0xb2f83c480b646128
    name: "c_0xb2f83c480b646128"
  - platform: ld2410
    ld2410_id: ld2410_1
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Distance Detection (cm)"
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy
    light:
      name: light
  - platform: uptime
    name: Uptime


switch:
  - platform: ld2410
    ld2410_id: ld2410_1
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"


number:
  - platform: ld2410
    ld2410_id: ld2410_1
    timeout:
      name: timeout
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
    light_threshold:
      name: light threshold



button:
  - platform: ld2410
    ld2410_id: ld2410_1
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart ld2410"
    query_params:
      name: query params
  - platform: restart
    name: Restart
    entity_category: diagnostic

text_sensor:
  - platform: ld2410
    ld2410_id: ld2410_1
    version:
      name: "firmware version"
    mac_address:
      name: "mac address"


select:
  - platform: ld2410
    ld2410_id: ld2410_1
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level