esphome:
  name: ld2420-bedroom

esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: esp-idf
    version: recommended

logger:

api:
  password: ""
ota:
  password: ""
  safe_mode: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true


light:
  - platform: binary
    name: "Indicator"
    output: indicator_output

output:
  - id: indicator_output
    platform: gpio
    pin: GPIO15
    inverted: false

uart:
  - rx_pin:
      number: GPIO13
      mode: INPUT
    tx_pin:
      number: GPIO14
      mode: OUTPUT
    baud_rate: 115200
    id: ld2420_uart


ld2420:

text_sensor:
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware

sensor:
  - platform: ld2420
    moving_distance:
      name : Moving Distance
  - platform: uptime
    name: Uptime
  - platform: internal_temperature
    name: "Internal Temperature"

binary_sensor:
  - platform: ld2420
    has_target:
      name: Presence

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode

number:
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum
    # See "Number" section below for detail
    gate_select:
      name: Select Gate to Set
    still_threshold:
      name: Set Still Threshold Value
    move_threshold:
      name: Set Move Threshold Value

button:
  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits
  - platform: restart
    name: "Reboot"