esphome:
  name: pet-scales
  friendly_name: pet-scales
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

logger:
  baud_rate: 115200

api:
  password: ""
ota:
  safe_mode: false
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

button:
  - platform: restart
    name: "Reboot"
sensor:
  - platform: hx711
    name: "weight"
    id: weight
#    device_class: "volume_storage"
    unit_of_measurement: "Kg"
    accuracy_decimals: 2
    dout_pin: GPIO4
    clk_pin: GPIO3
    gain: 128
    update_interval: 1s
    filters:
      - calibrate_linear:
          - 525790 -> 0
          - 834290 -> 1
  - platform: template
    name: "True weight"
    unit_of_measurement: "Kg"
    accuracy_decimals: 2
    update_interval: 1s
    lambda:
      return id(weight).state;
    filters:
      - filter_out: NAN
      - median:
          window_size: 5
          send_every: 4
          send_first_at: 3


  - platform: uptime
    name: Uptime

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_ON

output:
  - id: indicator_output
    platform: gpio
    pin: GPIO8
    inverted: true