esphome:
  name: pet-feeder
  friendly_name: pet-feeder

esp8266:
  board: esp01_1m
    
logger:
  baud_rate: 0

api:
  password: ""
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true


uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:

switch:
  - platform: "tuya"
    name: "Indicator light"
    switch_datapoint: 19
    
number:
  - platform: "tuya"
    name: "Feed portions"
    icon: mdi:tray-arrow-down
    number_datapoint: 3
    min_value: 0
    max_value: 3
    step: 1
    
    
text_sensor:
    
    
sensor:
  - platform: "tuya"
    name: "Fed portions"
    sensor_datapoint: 15
  - platform: "tuya"
    name: "Feeding state"
    sensor_datapoint: 4
  - platform: "tuya"
    name: "Food reserve"
    icon: mdi:tray-full
    sensor_datapoint: 102

output:
  - platform: esp8266_pwm
    pin: GPIO2
    frequency: 1000 Hz
    id: pwm_output

light:
  - platform: monochromatic
    icon: mdi:light-recessed
    output: pwm_output
    name: "Food light"