esphome:
  name: pet-scales
  friendly_name: pet-scales
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    priority: 500
    then:
      - light.turn_on:
          id: rgb_led
          effect: "Rainbow"
          brightness: 100%
esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

logger:
  baud_rate: 115200

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

button:
  - platform: restart
    name: "Reboot"
sensor:
  - platform: hx711
    name: "weight"
    id: weight
#    device_class: "volume_storage"
    unit_of_measurement: "Kg"
    accuracy_decimals: 2
    dout_pin: GPIO4
    clk_pin: GPIO3
    gain: 128
    update_interval: 1s
    filters:
      - calibrate_linear:
          - 525790 -> 0
          - 834290 -> 1
  - platform: template
    name: "True weight"
    unit_of_measurement: "Kg"
    accuracy_decimals: 2
    update_interval: 1s
    lambda:
      return id(weight).state;
    filters:
      - filter_out: NAN
      - median:
          window_size: 5
          send_every: 4
          send_first_at: 3


  - platform: uptime
    name: Uptime

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_ON

  - platform: esp32_rmt_led_strip
    id: rgb_led
    rgb_order: RGB
    chipset: SK6812
    pin: GPIO6
    num_leds: 23
    rmt_channel: 1
    name: "RGB Led"
    default_transition_length: 100ms
    restore_mode: ALWAYS_OFF
    effects:
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - addressable_rainbow:
          name: Rainbow
          speed: 6
          width: 1250
      - addressable_color_wipe:
          name: Color Wipe
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 5
              gradient: true
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false

output:
  - id: indicator_output
    platform: gpio
    pin:
      number: GPIO8
      ignore_strapping_warning: true
    inverted: true