esphome:
  name: rp2040-test
  friendly_name: rp2040-test
  on_boot:
    priority: 500
    then:
      - light.turn_on:
          id: rgb_led
          effect: "Random"
          brightness: 20%

rp2040:
  board: rpipicow

logger:
  baud_rate: 115200

light:
  - platform: rp2040_pio_led_strip
    pin: GPIO16
    num_leds: 1
    pio: 0
    rgb_order: GRB
    chipset: WS2812B
    name: "RGB Led"
    id: rgb_led
    default_transition_length: 100ms
    restore_mode: ALWAYS_OFF
    effects:
      - random:
          name: "Random"
          transition_length: 0s
          update_interval: 1s
      - addressable_rainbow:
          name: Rainbow
          speed: 6
          width: 1250
      - addressable_color_wipe:
          name: Color Wipe
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 5
              gradient: true
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false