esphome:
  name: sonoff-minir4-01
  friendly_name: sonoff-minir4-01

esp32:
  board: esp32dev
  framework:
    type: arduino


logger:

api:
  password: ""
ota:
  safe_mode: false
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true


status_led:
  pin:
    number: GPIO19
    inverted: true

switch:
  - platform: gpio
    pin: GPIO26
    name: "Relay"
    id: relay_01
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 60s
      - switch.turn_off: relay_01

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: button
    filters:
      - invert:
      - delayed_off: 50ms
    on_press:
      - switch.toggle:
          id: relay_01

  - platform: gpio
    pin: GPIO27
    id: s1
    filters:
      - invert:
      - delayed_off: 50ms
    on_press:
      then:
        - switch.toggle:
            id: relay_01

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
  - platform: uptime
    name: Uptime