esphome:
  name: sonoff-minir4-03
  friendly_name: sonoff-minir4-03

esp32:
  board: esp32dev
  framework:
    type: esp-idf


logger:
  baud_rate: 0

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

remote_transmitter:
  pin: GPIO1
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

status_led:
  pin:
    number: GPIO19
    inverted: true

switch:
  - platform: gpio
    pin: GPIO26
    name: "Relay"
    id: relay_01
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: button01
    filters:
      - invert:
      - delayed_off: 50ms
    on_press:
      - switch.toggle:
          id: relay_01

  - platform: gpio
    pin: GPIO27
    id: s1
    filters:
      - invert:
      - delayed_off: 50ms
    on_press:
      then:
        - switch.toggle:
            id: relay_01

  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
    id: button02
    name: button02
    filters:
      - invert:
      - delayed_off: 50ms

button:
  - platform: template
    name: "projector power"
    icon: mdi:power
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xF40B

  - platform: template
    name: "projector input"
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xF30C

  - platform: template
    name: "projector down"
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xAC53

  - platform: template
    name: "projector ok"
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xF708
        command: 0xE31C

  - platform: template
    name: "soundbar power"
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xB683
        command: 0xB24D

  - platform: template
    name: "soundbar vol up"
    on_press:
      remote_transmitter.transmit_nec:
        address: 0xB683
        command: 0xF40B

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
  - platform: uptime
    name: Uptime