esphome:
  name: test-dallas
  friendly_name: test-dallas

esp8266:
  board: d1_mini

logger:

api:
  password: ""
ota:
  password: ""
  safe_mode: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  output_power: 20.5dbm
  power_save_mode: none
dallas:
  - pin: D4
    id: ds_cheap
  - pin: D3
    id: ds_expen

sensor:
  - platform: dallas
    dallas_id: ds_cheap
    address: 0xe2b808480b646128
    name: "c_0xe2b808480b646128"
  - platform: dallas
    dallas_id: ds_cheap
    address: 0xb2f83c480b646128
    name: "c_0xb2f83c480b646128"
  - platform: dallas
    dallas_id: ds_cheap
    address: 0x0e1926480b646128
    name: "c_0x0e1926480b646128"
  - platform: dallas
    dallas_id: ds_cheap
    address: 0x4feb2b480b646128
    name: "c_0x4feb2b480b646128"
  - platform: dallas
    dallas_id: ds_cheap
    address: 0x8e64fe490b646128
    name: "c_0x8e64fe490b646128"
  - platform: dallas
    dallas_id: ds_cheap
    address: 0x6ec30d490b646128
    name: "c_0x6ec30d490b646128"
  - platform: dallas
    dallas_id: ds_cheap
    address: 0x9ebb37490b646128
    name: "c_0x9ebb37490b646128"
  - platform: dallas
    dallas_id: ds_cheap
    address: 0x6554414b0b646128
    name: "c_0x6554414b0b646128"
  - platform: dallas
    dallas_id: ds_cheap
    address: 0xf23e6d4b0b646128
    name: "c_0xf23e6d4b0b646128"
  - platform: dallas
    dallas_id: ds_cheap
    address: 0x44fa434b0b646128
    name: "c_0x44fa434b0b646128"

  - platform: dallas
    dallas_id: ds_expen
    address: 0x4a0000003e9cc028
    name: "e_0x4a0000003e9cc028"
  - platform: dallas
    dallas_id: ds_expen
    address: 0x7e0000003c1fe028
    name: "e_0x7e0000003c1fe028"
  - platform: dallas
    dallas_id: ds_expen
    address: 0x580000003a35c428
    name: "e_0x580000003a35c428"
  - platform: dallas
    dallas_id: ds_expen
    address: 0xa20000003beed428
    name: "e_0xa20000003beed428"
  - platform: dallas
    dallas_id: ds_expen
    address: 0x620000003d55a628
    name: "e_0x620000003d55a628"
  - platform: dallas
    dallas_id: ds_expen
    address: 0x360000003d2d1628
    name: "e_0x360000003d2d1628"
  - platform: dallas
    dallas_id: ds_expen
    address: 0x820000003d6f0128
    name: "e_0x820000003d6f0128"
  - platform: dallas
    dallas_id: ds_expen
    address: 0x3b0000003e59e128
    name: "e_0x3b0000003e59e128"
  - platform: dallas
    dallas_id: ds_expen
    address: 0x980000003b828b28
    name: "e_0x980000003b828b28"
  - platform: dallas
    dallas_id: ds_expen
    address: 0x000000003e505b28
    name: "e_0x000000003e505b28"


