esphome:
  name: tuya-16a-mini-smart-switch-01
  friendly_name: tuya-16a-mini-smart-switch-01

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev

logger:
  baud_rate: 0

api:
  password: ""
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  output_power: 20.5dbm
  power_save_mode: none

switch:
  - platform: gpio
    pin: P7
    inverted: false
    id: switch_01
    name: "Switch"
    restore_mode: RESTORE_DEFAULT_OFF

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_OFF

output:
  - id: indicator_output
    platform: gpio
    pin: P26
    inverted: false

binary_sensor:
  - platform: gpio
    id: button_01
    pin:
      number: P23
      inverted: true
    on_press:
      if:
        condition:
          - switch.is_on: switch_01
        then:
          - light.turn_off: indicator_light
          - switch.turn_off: switch_01
        else:
          - light.turn_on: indicator_light
          - switch.turn_on: switch_01

sensor:
  - platform: uptime
    name: Uptime

button:
  - platform: restart
    name: "Restart"