esphome:
  name: tuya-16a-mini-smart-switch-01
  friendly_name: tuya-16a-mini-smart-switch-01

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev

logger:
  baud_rate: 0

api:
  password: ""
ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

switch:
  - platform: gpio
    pin: P7
    inverted: false
    id: switch_01
    name: "Switch"
    restore_mode: ALWAYS_ON

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_OFF

output:
  - id: indicator_output
    platform: gpio
    pin: P26
    inverted: false

binary_sensor:
  - platform: gpio
    id: button_01
    pin:
      number: P23
      inverted: true
#    on_state:
#      then:
#        - light.toggle: indicator_light

sensor:
  - platform: uptime
    name: Uptime

button:
  - platform: restart
    name: "Restart"