esphome:
  name: ty-diy-s02
  friendly_name: ty-diy-s02

esp8266:
  board: esp8285

logger:
  baud_rate: 0

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:
  status_pin: GPIO13

switch:
  - platform: "tuya"
    name: "Channel 1"
    id: sw_ch_01
    switch_datapoint: 1
    on_turn_on:
      - delay: 60s
      - switch.turn_off: sw_ch_01
  - platform: "tuya"
    name: "Channel 2"
    id: sw_ch_02
    switch_datapoint: 2
    on_turn_on:
      - delay: 60s
      - switch.turn_off: sw_ch_02
  - platform: "tuya"
    name: "Power on status"
    switch_datapoint: 101


select:
  - platform: "tuya"
    name: "Switch mode"
    enum_datapoint: 102
    optimistic: false
    options:
      0: "Always on"
      1: "Inching"
      2: "Interlock"

sensor:
  - platform: uptime
    name: Uptime
