esphome:
  name: water-temp
  friendly_name: water-temp
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: arduino
    version: recommended

psram:
  mode: quad
  speed: 80MHz

udp:
  update_interval: 1s
  providers:
    - name: watermeter-02
    - name: ld2410-v2-bathroom

logger:
  baud_rate: 0
  level: INFO

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

time:
  - platform: homeassistant
    id: esptime
    timezone: Europe/Moscow


i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  frequency: 400kHz
  #timeout: 13ms

one_wire:
  - platform: gpio
    pin:
      number: GPIO21
      mode:
        input: true
        pullup: true

font:
  - file: "fonts/4x6.bdf"
    id: f4x6
    size: 6
  - file: "fonts/5x8.bdf"
    id: f5x8
  - file: "fonts/10x20.bdf"
    id: f10x20
  - file: "fonts/helvR08.bdf"
    id: fh08

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    update_interval: 100ms
    rotation: 180
    lambda: |-
      
      if(!isnan(id(presence).state) && id(presence).state == false) {
        //it.print(rand() % 100, rand() % 60, id(f4x6), "Who are you?");
        return;
      }
      
      //it.print(0, 0, id(f10x20), "ON");
      
      esphome::ESPTime now = id(esptime).now();
      it.strftime(80, 0, id(f10x20), "%H", now);
      it.print(98, 0, id(f10x20), ":");
      it.strftime(106, 0, id(f10x20), "%M", now);

      //it.strftime(0, 0, id(f10x20), "%H", now);
      //it.print(18, 0, id(f10x20), ":");
      //it.strftime(26, 0, id(f10x20), "%M", now);

      it.printf(0, 0, id(f10x20), "%.1f°C", id(temp).state);
      
      it.printf(0, 16, id(fh08), "C: %.1fL, %.1fL/min", id(cold_water_current_run).state, id(cold_water_flow).state);
      it.printf(0, 27, id(fh08), "H: %.1fL, %.1fL/min", id(hot_water_current_run).state, id(hot_water_flow).state);
      it.printf(0, 38, id(fh08), "Totals:");
      it.printf(0, 49, id(fh08), "C: %.0fL, H: %.0fL", id(cold_water_usage).state, id(hot_water_usage).state);
      
      return;

button:
  - platform: restart
    name: "Reboot"

sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: dallas_temp
    address: 0x980000003b828b28
    id: temp
    name: "temperature"
    update_interval: 1s
    internal: true

  - platform: udp
    provider: watermeter-02
    name: "cold water usage"
    remote_id: cold_water_usage
    id: cold_water_usage
    internal: true

  - platform: udp
    provider: watermeter-02
    name: "cold water flow"
    remote_id: cold_water_flow
    id: cold_water_flow
    internal: true

  - platform: udp
    provider: watermeter-02
    name: "cold water current run"
    remote_id: cold_water_current_run
    id: cold_water_current_run
    internal: true

  - platform: udp
    provider: watermeter-02
    name: "hot water usage"
    remote_id: hot_water_usage
    id: hot_water_usage
    internal: true

  - platform: udp
    provider: watermeter-02
    name: "hot water flow"
    remote_id: hot_water_flow
    id: hot_water_flow
    internal: true

  - platform: udp
    provider: watermeter-02
    name: "hot water current run"
    remote_id: hot_water_current_run
    id: hot_water_current_run
    internal: true


binary_sensor:
  - platform: udp
    provider: ld2410-v2-bathroom
    remote_id: presence
    name: "bathroom presence"
    id: presence
    internal: true
    on_press:
      then:
          - light.turn_on: indicator_light
    on_release:
      then:
        - light.turn_off: indicator_light

#status_led:
#  pin:
#    number: GPIO15
#    inverted: false

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_OFF
    internal: true

output:
  - id: indicator_output
    platform: gpio
    pin: GPIO15
    inverted: false
