esphome:
  name: watermeter-02
  friendly_name: watermeter-02
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf
    version: recommended


logger:
  baud_rate: 0

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  output_power: 15dbm


button:
  - platform: restart
    name: "Reboot"
sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    #update_interval: 2s

  - platform: pulse_meter
    pin:
      number: GPIO1
      mode:
        input: true
        pullup: false
        pulldown: false
      inverted: true
    id: meter_01
    name: "cold water flow"
    device_class: volume_flow_rate
    #update_interval: 1s
    timeout: 2s
    internal_filter_mode: PULSE
    internal_filter: 0.002s
    unit_of_measurement: "L/min"
    filters:
      - lambda: return (x * 1 / 400);
    total:
      name: "cold water usage"
      device_class: water
      id: counter_cold_total
      icon: "mdi:water"
      accuracy_decimals: 2
      unit_of_measurement: "L"
      filters:
        - lambda: return (x * 1 / 400);
    on_raw_value:
      - light.toggle:
          id: indicator_light

  - platform: pulse_meter
    pin:
      number: GPIO2
      mode:
        input: true
        pullup: false
        pulldown: false
      inverted: true
    id: meter_02
    name: "hot water flow"
    device_class: volume_flow_rate
    #update_interval: 1s
    timeout: 2s
    internal_filter_mode: PULSE
    internal_filter: 0.002s
    unit_of_measurement: "L/min"
    filters:
      - lambda: return (x * 1 / 400);
    total:
      name: "hot water usage"
      device_class: water
      id: counter_hot_total
      icon: "mdi:water"
      accuracy_decimals: 2
      unit_of_measurement: "L"
      filters:
        - lambda: return (x * 1 / 400);
    on_raw_value:
      - light.toggle:
          id: indicator_light


light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_ON
    internal: true

output:
  - id: indicator_output
    platform: gpio
    pin:
      number: GPIO8
      ignore_strapping_warning: true
    inverted: true