esphome:
  name: water-temp
  friendly_name: water-temp
  platformio_options:
    board_build.flash_mode: dio


esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: arduino
    version: recommended

logger:
  baud_rate: 115200

api:
  password: ""
ota:
  platform: esphome
  password: ""
safe_mode:
  disabled: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

time:
  - platform: homeassistant
    id: esptime
    timezone: Europe/Moscow


i2c:
  sda: GPIO33
  scl: GPIO18
  scan: true
  frequency: 400kHz

one_wire:
  - platform: gpio
    pin: GPIO17

font:
  - file: "fonts/4x6.bdf"
    id: f4x6
    size: 6
  - file: "fonts/5x8.bdf"
    id: f5x8
  - file: "fonts/10x20.bdf"
    id: f10x20
  - file: "fonts/helvR08.bdf"
    id: fh08

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    update_interval: 100ms
    lambda: |-
      
      if(!isnan(id(presence).state) && id(presence).state == false) {
        //it.print(rand() % 100, rand() % 60, id(f4x6), "Who are you?");
        return;
      }
      
      //it.print(0, 0, id(f10x20), "ON");
      
      esphome::ESPTime now = id(esptime).now();
      it.strftime(0, 0, id(f10x20), "%H", now);
      it.print(18, 0, id(f10x20), ":");
      it.strftime(26, 0, id(f10x20), "%M", now);

      it.printf(0, 16, id(f10x20), "%.1f°C", id(temp).state);
      return;

button:
  - platform: restart
    name: "Reboot"

sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    #update_interval: 2s

  - platform: dallas_temp
    address: 0x980000003b828b28
    id: temp
    name: "temperature"
    update_interval: 1s

binary_sensor:
  - platform: homeassistant
    name: "bathroom presence"
    entity_id: binary_sensor.ld2410_v2_bathroom_presence
    id: presence

light:
  - platform: binary
    id: indicator_light
    name: "Indicator"
    output: indicator_output
    restore_mode: ALWAYS_OFF
    internal: true

output:
  - id: indicator_output
    platform: gpio
    pin: GPIO15
    inverted: false
